# ControlPlane-inspired MinIO deployment
# Adapted for local Docker deployment

version: '3.8'

services:
  # MinIO Storage Server (ControlPlane style single container)
  minio:
    image: minio/minio:latest
    hostname: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio-network

  # Nginx Load Balancer (ControlPlane style proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"      # HTTP access
      - "443:443"    # HTTPS access (if needed)
    volumes:
      - ./nginx-controlplane.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    networks:
      - minio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: MinIO Client for testing
  mc-client:
    image: minio/mc:latest
    entrypoint: ["/bin/sh"]
    command: ["-c", "sleep infinity"]
    networks:
      - minio-network
    profiles:
      - testing

volumes:
  minio-data:
    driver: local

networks:
  minio-network:
    driver: bridge